common_words = [
    "a", "about", "above", "across", "act", "add", "after", "again", "against", "age", "ago", "air",
    "all", "allow", "almost", "alone", "along", "already", "also", "although", "always", "among", "an",
    "and", "animal", "another", "answer", "any", "appear", "area", "arm", "around", "arrive", "art", "as",
    "ask", "at", "away", "baby", "back", "bad", "bag", "ball", "bank", "base", "be", "bear", "beat",
    "beautiful", "bed", "been", "before", "begin", "behind", "believe", "below", "best", "better",
    "between", "big", "bird", "bit", "black", "blood", "blue", "board", "body", "book", "both",
    "bottom", "box", "boy", "bring", "brother", "build", "building", "burn", "business", "busy", "but",
    "buy", "by", "call", "came", "can", "car", "care", "carry", "case", "cat", "cause", "center",
    "century", "certain", "chair", "change", "check", "child", "choose", "church", "city", "class",
    "clean", "clear", "climb", "close", "cold", "color", "come", "common", "company", "compare",
    "complete", "condition", "consider", "continue", "control", "cost", "could", "country", "course",
    "cover", "create", "cross", "cry", "cup", "current", "cut", "day", "dead", "deal", "death", "debate",
    "decide", "decision", "deep", "defense", "degree", "Democrat", "democratic", "describe", "design",
    "despite", "detail", "determine", "develop", "development", "die", "difference", "different",
    "difficult", "dinner", "direction", "director", "discover", "discuss", "discussion", "disease", "do",
    "doctor", "dog", "door", "down", "draw", "dream", "drive", "drop", "drug", "during", "each", "early",
    "east", "easy", "eat", "economic", "economy", "edge", "education", "effect", "effort", "eight",
    "either", "election", "else", "employee", "end", "energy", "enjoy", "enough", "enter", "entire",
    "environment", "environmental", "especially", "establish", "even", "evening", "event", "ever",
    "every", "everybody", "everyone", "everything", "evidence", "exactly", "example", "executive",
    "exist", "expect", "experience", "expert", "explain", "eye", "face", "fact", "factor", "fail", "fall",
    "family", "far", "fast", "father", "fear", "federal", "feel", "feeling", "few", "field", "fight",
    "figure", "fill", "film", "final", "finally", "financial", "find", "fine", "finger", "finish", "fire",
    "firm", "first", "fish", "five", "floor", "fly", "focus", "follow", "food", "foot", "for", "force",
    "foreign", "forget", "form", "former", "forward", "four", "free", "friend", "from", "front", "full",
    "fund", "future", "game", "garden", "gas", "general", "generation", "get", "girl", "give", "glass",
    "go", "goal", "good", "government", "great", "green", "ground", "group", "grow", "growth", "guess",
    "gun", "guy", "hair", "half", "hand", "hang", "happen", "happy", "hard", "have", "he", "head",
    "health", "hear", "heart", "heat", "heavy", "help", "her", "here", "herself", "high", "him",
    "himself", "his", "history", "hit", "hold", "home", "hope", "hospital", "hot", "hotel", "hour",
    "house", "how", "however", "huge", "human", "hundred", "husband", "I", "idea", "identify", "if",
    "image", "imagine", "impact", "important", "improve", "in", "include", "including", "increase",
    "indeed", "indicate", "individual", "industry", "information", "inside", "instead", "institution",
    "interest", "interesting", "international", "interview", "into", "investment", "involve", "issue",
    "it", "item", "its", "itself", "job", "join", "just", "keep", "key", "kid", "kill", "kind", "kitchen",
    "know", "knowledge", "land", "language", "large", "last", "late", "later", "laugh", "law", "lawyer",
    "lay", "lead", "leader", "learn", "least", "leave", "left", "leg", "legal", "less", "let", "letter",
    "level", "lie", "life", "light", "like", "likely", "line", "list", "listen", "little", "live",
    "local", "long", "look", "lose", "loss", "lot", "love", "low", "machine", "magazine", "main",
    "maintain", "major", "majority", "make", "man", "manage", "management", "manager", "many", "market",
    "marriage", "material", "matter", "may", "maybe", "me", "mean", "measure", "media", "medical",
    "meet", "meeting", "member", "memory", "mention", "message", "method", "middle", "might", "military",
    "million", "mind", "minute", "miss", "mission", "model", "modern", "moment", "money", "month",
    "more", "morning", "most", "mother", "mouth", "move", "movement", "movie", "Mr", "Mrs", "much",
    "music", "must", "my", "myself", "name", "nation", "national", "natural", "nature", "near",
    "nearly", "necessary", "need", "network", "never", "new", "news", "newspaper", "next", "nice",
    "night", "no", "none", "nor", "north", "not", "note", "nothing", "notice", "now", "number", "occur",
    "of", "off", "offer", "office", "officer", "official", "often", "oh", "oil", "ok", "old", "on",
    "once", "one", "only", "onto", "open", "operation", "opportunity", "option", "or", "order",
    "organization", "other", "others", "our", "out", "outside", "over", "own", "owner", "page", "pain",
    "painting", "paper", "parent", "part", "participant", "particular", "particularly", "partner",
    "party", "pass", "past", "patient", "pattern", "pay", "peace", "people", "per", "perform",
    "performance", "perhaps", "period", "person", "personal", "phone", "physical", "pick", "picture",
    "piece", "place", "plan", "plant", "play", "player", "PM", "point", "police", "policy", "political",
    "politics", "poor", "popular", "population", "position", "positive", "possible", "power",
    "practice", "prepare", "present", "president", "pressure", "pretty", "prevent", "price", "private",
    "probably", "problem", "process", "produce", "product", "production", "professional", "professor",
    "program", "project", "property", "protect", "prove", "provide", "public", "pull", "purpose",
    "push", "put", "quality", "question", "quickly", "quite", "race", "radio", "raise", "range",
    "rate", "rather", "reach", "read", "ready", "real", "reality", "realize", "really", "reason",
    "receive", "recent", "recently", "recognize", "record", "red", "reduce", "reflect", "region",
    "relate", "relationship", "religious", "remain", "remember", "remove", "report", "represent",
    "Republican", "require", "research", "resource", "respond", "response", "responsibility", "rest",
    "result", "return", "reveal", "rich", "right", "rise", "risk", "road", "rock", "role", "room",
    "rule", "run", "safe", "same", "save", "say", "scene", "school", "science", "scientist", "score",
    "sea", "season", "seat", "second", "section", "security", "see", "seek", "seem", "sell", "send",
    "senior", "sense", "series", "serious", "serve", "service", "set", "seven", "several", "sex",
    "sexual", "shake", "share", "she", "shoot", "short", "shot", "should", "shoulder", "show", "side",
    "sign", "significant", "similar", "simple", "simply", "since", "sing", "single", "sister", "sit",
    "site", "situation", "six", "size", "skill", "skin", "small", "smile", "so", "social", "society",
    "soldier", "some", "somebody", "someone", "something", "sometimes", "son", "song", "soon", "sort",
    "sound", "source", "south", "southern", "space", "speak", "special", "specific", "speech",
    "spend", "sport", "spring", "staff", "stage", "stand", "standard", "star", "start", "state",
    "statement", "station", "stay", "step", "still", "stock", "stop", "store", "story", "strategy",
    "street", "strong", "structure", "student", "study", "stuff", "style", "subject", "success",
    "successful", "such", "suddenly", "suffer", "suggest", "summer", "support", "sure", "surface",
    "system", "table", "take", "talk", "task", "tax", "teach", "teacher", "team", "technology",
    "television", "tell", "ten", "tend", "term", "test"
]
